keys:
  - &tetov_age age1xv6x97jjzp222csf73m5782aj9lqj8tudqjzdj0sj28y3u6n9gmqunmyfz
  # - &kaolin-nixos_host
creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
        - *tetov_age
