# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --flake --nixfmt --no-shell --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  geometry-msgs,
  launch,
  launch-ros,
  rclpy,
  rosidl-default-generators,
  rosidl-default-runtime,
  std-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-industrial-reconstruction-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ros-industrial";
    repo = "industrial_reconstruction";
    rev = "05f4215510fbc33d6a216774aea85505efa49e63";
    sha256 = "07sfb28j06cmwv4816js6p48bpasclg6qn4v59ms194k7g44q8dk";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/industrial_reconstruction_msgs/";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  propagatedBuildInputs = [
    geometry-msgs
    launch
    launch-ros
    rclpy
    rosidl-default-runtime
    std-msgs
    tf2-ros
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "A collection of ROS interfaces for industrial_reconstruction";
    license = with lib.licenses; [ asl20 ];
  };
}
