/rgbd_camera:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_nn_type: none
      i_ip: 192.168.8.10
      i_pipeline_dump: true
    stereo:
      i_subpixel: true
      i_align_depth: true
