/rgbd_camera:
  ros__parameters:
    camera:
      i_nn_type: none
      i_mx_id: 18443010C10B361300
    stereo:
      subpixel: true
    # rgbd_camera:
    #   rgb:
    #     image_raw:
    #       enable_pub_plugins:
    #         - image_transport/zstd
    #         - image_transport/raw
    #   stereo:
    #     image_raw:
    #       enable_pub_plugins:
    #         - image_transport/zstd
    #         - image_transport/raw
