/rgbd_camera:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_nn_type: none
      i_ip: 192.168.8.10
    stereo:
      i_align_depth: true
      i_low_bandwidth: true
      i_fps: 5.0
    rgb:
      i_low_bandwidth: true
      i_fps: 5.0
    left:
      i_low_bandwidth: true
      i_fps: 5.0
    right:
      i_low_bandwidth: true
      i_fps: 5.0
