/rob1/rgbd/extruder_OAK_D_S2_POE:
  ros__parameters:
    driver:
      i_low_bandwidth: true
    pipeline_gen:
      i_pipeline_type: RGBD
    stereo:
      i_align_depth: true
      i_low_bandwidth: true
    rgb:
      i_low_bandwidth: true
