# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --flake --nixfmt --no-shell --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  cv-bridge,
  geometry-msgs,
  industrial-reconstruction-msgs,
  launch,
  launch-ros,
  message-filters,
  python3Packages,
  rclpy,
  sensor-msgs,
  std-msgs,
  tf2-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-industrial-reconstruction";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ros-industrial";
    repo = "industrial_reconstruction";
    rev = "90fdc690be9230480614b5cf96cc39c873de292c";
    sha256 = "sha256-XHYAjOkXwgZFZhBZ5bsEVhhNiOGMivRZJaNhOnTDimQ=";
  };

  buildType = "ament_python";
  sourceRoot = "${src.name}/industrial_reconstruction/";

  nativeBuildInputs = [ ament-cmake ];

  buildInputs = [ ament-cmake ];

  propagatedBuildInputs = [
    cv-bridge
    geometry-msgs
    industrial-reconstruction-msgs
    launch
    launch-ros
    message-filters
    rclpy
    sensor-msgs
    std-msgs
    tf2-msgs
    tf2-ros
    visualization-msgs
  ]
  ++ (with python3Packages; [
    open3d
    pyquaternion
  ]);

  meta = {
    description = "A ROS2 reconstruction utility leveraging TSDF from Open3D";
    license = with lib.licenses; [ asl20 ];
  };
}
