/rgbd/d405:
  ros__parameters:
    enable_color: true
    enable_depth: true
    depth_module:
      depth_profile: 848x480x30
      color_profile: 848x480x30
      infra_profile: 848x480x30
    # decimation_filter:
    #   enable: true
    # hole_filling_filter:
    #   enable: true
    # spatial_filter:
    #   enable: true
    # pointcloud:
    #   enable: false
    #   stream_filter: 3
    # enable_color: true
    # pointcloud:
    #   enable: true
    # enable_depth: true
    # enable_color: true
    # pointcloud:
    #   enable: true
