/**:
  ros__parameters:
    # Basic setup
    map_frame: map
    robot_frame: base_link
    max_range: 3.0
    resolution: 0.02
    prob_hit: 0.99
    prob_miss: 0.1
    thres_min: 0.49
    thres_max: 0.51
    map_save_dir: ""
    fast_mode: true
    # Visualizations
    publish_pointcloud: true
    publish_vis_marker: true
    publish_occupancy_grid: true
    visualization_rate: 2.0
    # Sensor input
    accumulate_updates: true
    accumulation_period: 0.2
    apply_raw_sensor_data: true
    sources: [oak]
    oak:
      topic: /rgbd_camera/points
      sensor_origin_frame: rgbd_camera
      reliable: true
