<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>biodigitalmatter_ros</name>
  <version>0.1.0</version>
  <description>ROS setup for biodigital matter lab</description>
  <maintainer email="anton@tetov.se">Anton Tetov Johansson</maintainer>
  <license>Apache-2.0</license>
  <url type="website">https://www.abm.lth.se/biodigitalmatter/</url>
  <url type="repository">https://github.com/biodigitalmatter/ros/</url>
  <url type="bugtracker">https://github.com/biodigitalmatter/ros/issues</url>

  <exec_depend>compas_rrc_driver</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>depthai-ros</exec_depend>
  <exec_depend>axis_camera</exec_depend>
  <exec_depend>abb_bringup</exec_depend>
  <exec_depend>abb_rws_client</exec_depend>
  <exec_depend>chess_vision</exec_depend>
  <!-- ros 1 compas_rrc -->
  <exec_depend>docker-compose</exec_depend>
  <!-- <exec_depend>octomap_server</exec_depend> -->
  <exec_depend>robot_calibration</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
