ARG ROS_DISTRO=jazzy

FROM docker.io/ros:${ROS_DISTRO}-ros-base AS builder

ARG ROS_DISTRO

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /ros2_ws

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      python3-colcon-common-extensions \
      python3-rosdep && \
		rm -rf /var/lib/apt/lists/*

COPY . ./src/elizabeth_perception

RUN apt-get update && \
    rosdep update && \
    rosdep install \
      --from-paths src \
      --ignore-src \
      --rosdistro ${ROS_DISTRO} \
			-y && \
    rm -rf /var/lib/apt/lists/*

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build \
      --merge-install \
      --cmake-args -DCMAKE_BUILD_TYPE=Release

FROM docker.io/ros:${ROS_DISTRO}-ros-base AS runtime

ARG ROS_DISTRO

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=${ROS_DISTRO}
WORKDIR /ros2_ws

COPY . ./src/elizabeth_perception

RUN apt-get update && \
		apt-get install -y --no-install-recommends \
      python3-rosdep && \
    rosdep update && \
    rosdep install \
      --from-paths src \
      --ignore-src \
      --rosdistro ${ROS_DISTRO} \
			-y && \
    rm -rf /var/lib/apt/lists/* src

COPY --from=builder /ros2_ws/install ./install

COPY ./container_entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["ros2", "launch", "elizabeth_perception", "rgbd.launch.yaml"]
