# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --flake --nixfmt --no-shell --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  cv-bridge,
  geometry-msgs,
  industrial-reconstruction-msgs,
  launch,
  launch-ros,
  message-filters,
  open3d,
  rclpy,
  sensor-msgs,
  std-msgs,
  tf2-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-industrial-reconstruction";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ros-industrial";
    repo = "industrial_reconstruction";
    rev = "05f4215510fbc33d6a216774aea85505efa49e63";
    sha256 = "07sfb28j06cmwv4816js6p48bpasclg6qn4v59ms194k7g44q8dk";
  };

  buildType = "ament_python";
  sourceRoot = "${src.name}/industrial_reconstruction/";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    cv-bridge
    geometry-msgs
    industrial-reconstruction-msgs
    launch
    launch-ros
    message-filters
    open3d
    rclpy
    sensor-msgs
    std-msgs
    tf2-msgs
    tf2-ros
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A ROS2 reconstruction utility leveraging TSDF from Open3D";
    license = with lib.licenses; [ asl20 ];
  };
}
