name: Build and test with colcon
on: [push]
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest@sha256:c597524065d7f76ecee5524d4bbc10f7895b4a36ffc8ce64657d113067dd2d40
    steps:
      - run: >
          echo "yaml file:///etc/ros/rosdep/compas_rule.yaml" >> /etc/ros/rosdep/sources.list.d/30-custom.list

      - run: |
          cat << EOF > /etc/ros/rosdep/compas_rule.yaml
          python3-compas:
            ubuntu:
              pip:
                packages: [compas]
          EOF
      - name: Explicitly install numpy<2 to system python so compas doesnt bring in numpy v2
        run: |
          PIP_BREAK_SYSTEM_PACKAGES=1 pip install numpy<2
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@3a640b10f09b756dabe556dac5413aba369f71b0 # v0.4.8
        with:
          target-ros2-distro: jazzy
