name: Build and test with colcon using nix-ros-overlay
on: [push]
jobs:
  build_and_test_ros2_with_nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: install nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          extra_nix_config: |
            trusted-public-keys = binarycache.tetov.se:84dA6GWAIObxcK+7BhlVreVThNAXELdtTX+i2fRipyE= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ros.cachix.org-1:dSyZxI8geDCJrwgvCOHDoAfOm5sV1wCPjBkKL+38Rvo=
            substituters = https://binarycache.tetov.se https: https://ros.cachix.org https://cache.nixos.org
      - name: Build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
      - name: nix flake check
        run: nix flake check --verbose --keep-going
